version: "3.8"

services:
  # Define your service(s) here
  web:
    image: drupal:9
    ports:
      - 8080:80
    restart: unless-stopped


  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=drupal
      - POSTGRES_USER=user



#networks:
  # Define any custom networks your services need
#  my-network





#drupal:9
#postgres:14